# Generated by Django 3.2.13 on 2022-06-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.TextField()),
            ],
        ),
    ]
