# Generated by Django 3.2.13 on 2022-06-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
