# Generated by Django 3.2.13 on 2022-06-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220622_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
