# Generated by Django 3.2.13 on 2022-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
    ]
